/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/src/env.d.ts` (hash: d5f4adaa12f4f85408fe0b10b5250a5c)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	FRONTEND_URL: "https://runriotcomeon.github.io/yixu-photo-atlas/";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FRONTEND_URL">> {}
}
